[default_apps]
terminal = "kitty"
browser = "zen-browser %U"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "chf"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 750
height = 474
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock/icons"]
icon_size = 22
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = false
animate = true

[binds]
up = "control-k"
down = "control-j"
left = "control-ih"
right = "control-l"
context = "control-i"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/pandadev/.config/sherlock/config.toml"
css = "/home/pandadev/.config/sherlock/main.css"
fallback = "/home/pandadev/.config/sherlock/fallback.json"
alias = "/home/pandadev/.config/sherlock/sherlock_alias.json"
ignore = "/home/pandadev/.config/sherlock/sherlockignore"
actions = "/home/pandadev/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = true
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "/home/pandadev/.cache/sherlock/sherlock_desktop_cache.json"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = true

[search_bar_icon]
enable = false
icon = "system-search-symbolic"
icon_back = "go-previous-symbolic"
size = 22
